import type {
  Brand,
  Goal,
  Idea,
  Kpi,
  Reminder,
  Task,
} from "./types";
import { generateId } from "./utils";

const BRAND_ID = "brand-natural-scents";

export const SEED_BRAND: Brand = {
  id: BRAND_ID,
  name: "Natural Scents",
  description: "Premium natural fragrance brand — creator & wholesale growth",
  stage: "Growth",
  monthly_revenue: 42000,
  priority_level: 1,
  categories: [
    "Creator Partnerships",
    "Wholesale",
    "Content",
    "Operations",
    "Customer Experience",
    "Finance",
    "Strategy",
  ],
  created_at: new Date().toISOString(),
};

export function getSeedData() {
  const now = new Date().toISOString();
  const weekLater = new Date(Date.now() + 7 * 86400000).toISOString().split("T")[0];
  const tomorrow = new Date(Date.now() + 86400000).toISOString().split("T")[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0];

  const goals: Goal[] = [
    {
      id: generateId(),
      title: "Reach $100k/month revenue",
      description: "Scale DTC and wholesale to hit six-figure monthly run rate",
      brand_id: BRAND_ID,
      type: "Monthly",
      target_metric: "Revenue",
      current_value: 42000,
      target_value: 100000,
      deadline: weekLater,
      status: "active",
      created_at: now,
    },
    {
      id: generateId(),
      title: "Build 100 active creator affiliates",
      description: "Creators posting with affiliate links monthly",
      brand_id: BRAND_ID,
      type: "Quarterly",
      target_metric: "Active creators",
      current_value: 34,
      target_value: 100,
      deadline: weekLater,
      status: "active",
      created_at: now,
    },
    {
      id: generateId(),
      title: "Open 25 wholesale accounts",
      description: "Retail and boutique wholesale partners",
      brand_id: BRAND_ID,
      type: "Quarterly",
      target_metric: "Wholesale accounts",
      current_value: 8,
      target_value: 25,
      deadline: weekLater,
      status: "active",
      created_at: now,
    },
    {
      id: generateId(),
      title: "Post 150 short-form videos this month",
      description: "TikTok, Reels, Shorts across brand accounts",
      brand_id: BRAND_ID,
      type: "Monthly",
      target_metric: "Videos posted",
      current_value: 62,
      target_value: 150,
      deadline: weekLater,
      status: "active",
      created_at: now,
    },
  ];

  const tasks: Task[] = [
    {
      id: generateId(),
      title: "Reach out to 100 creators",
      description: "DM + email outreach batch for March",
      brand_id: BRAND_ID,
      category: "Creator Partnerships",
      status: "In Progress",
      priority: "Critical",
      due_date: weekLater,
      reminder_date: null,
      estimated_impact: 5,
      effort_level: 4,
      created_at: now,
      completed_at: null,
    },
    {
      id: generateId(),
      title: "Create wholesale pitch email",
      description: "One-pager + sample offer for retail buyers",
      brand_id: BRAND_ID,
      category: "Wholesale",
      status: "To Do",
      priority: "High",
      due_date: tomorrow,
      reminder_date: null,
      estimated_impact: 4,
      effort_level: 2,
      created_at: now,
      completed_at: null,
    },
    {
      id: generateId(),
      title: "Review best-selling scents",
      description: "Inventory and margin analysis on top SKUs",
      brand_id: BRAND_ID,
      category: "Operations",
      status: "To Do",
      priority: "Medium",
      due_date: weekLater,
      reminder_date: null,
      estimated_impact: 3,
      effort_level: 2,
      created_at: now,
      completed_at: null,
    },
    {
      id: generateId(),
      title: "Plan next TikTok content batch",
      description: "15 hooks + scripts for filming day",
      brand_id: BRAND_ID,
      category: "Content",
      status: "Inbox",
      priority: "High",
      due_date: tomorrow,
      reminder_date: null,
      estimated_impact: 4,
      effort_level: 3,
      created_at: now,
      completed_at: null,
    },
    {
      id: generateId(),
      title: "Follow up with warm retail leads",
      description: "5 boutiques from trade show",
      brand_id: BRAND_ID,
      category: "Wholesale",
      status: "Waiting",
      priority: "High",
      due_date: yesterday,
      reminder_date: null,
      estimated_impact: 5,
      effort_level: 2,
      created_at: now,
      completed_at: null,
    },
  ];

  const ideas: Idea[] = [
    {
      id: generateId(),
      title: "Creator gifting campaign",
      description: "Send discovery sets to micro-creators in niche",
      brand_id: BRAND_ID,
      category: "Creator",
      priority: "High",
      status: "Considering",
      estimated_impact: 5,
      effort_level: 3,
      created_at: now,
    },
    {
      id: generateId(),
      title: "Scent discovery quiz",
      description: "On-site quiz → personalized product rec",
      brand_id: BRAND_ID,
      category: "Product",
      priority: "High",
      status: "Raw Idea",
      estimated_impact: 4,
      effort_level: 4,
      created_at: now,
    },
    {
      id: generateId(),
      title: "Wholesale sample box",
      description: "Curated 6-pack for retail buyers",
      brand_id: BRAND_ID,
      category: "Wholesale",
      priority: "Medium",
      status: "Raw Idea",
      estimated_impact: 4,
      effort_level: 2,
      created_at: now,
    },
    {
      id: generateId(),
      title: "TikTok street interview campaign",
      description: "What's your signature scent? → brand tie-in",
      brand_id: BRAND_ID,
      category: "Content",
      priority: "Medium",
      status: "Raw Idea",
      estimated_impact: 3,
      effort_level: 2,
      created_at: now,
    },
    {
      id: generateId(),
      title: "Subscription scent club",
      description: "Monthly refill subscription tier",
      brand_id: BRAND_ID,
      category: "Product",
      priority: "Medium",
      status: "Considering",
      estimated_impact: 5,
      effort_level: 4,
      created_at: now,
    },
  ];

  const kpis: Kpi[] = [
    {
      id: generateId(),
      brand_id: BRAND_ID,
      name: "Monthly revenue",
      value: 42000,
      target_value: 100000,
      period: "Monthly",
      date: new Date().toISOString().split("T")[0],
      notes: null,
    },
    {
      id: generateId(),
      brand_id: BRAND_ID,
      name: "Creators contacted",
      value: 78,
      target_value: 100,
      period: "Weekly",
      date: new Date().toISOString().split("T")[0],
      notes: null,
    },
    {
      id: generateId(),
      brand_id: BRAND_ID,
      name: "Wholesale leads",
      value: 12,
      target_value: 25,
      period: "Monthly",
      date: new Date().toISOString().split("T")[0],
      notes: null,
    },
    {
      id: generateId(),
      brand_id: BRAND_ID,
      name: "Content posts",
      value: 62,
      target_value: 150,
      period: "Monthly",
      date: new Date().toISOString().split("T")[0],
      notes: null,
    },
    {
      id: generateId(),
      brand_id: BRAND_ID,
      name: "Website conversion rate",
      value: 2.4,
      target_value: 3.5,
      period: "Weekly",
      date: new Date().toISOString().split("T")[0],
      notes: "%",
    },
  ];

  const reminders: Reminder[] = [
    {
      id: generateId(),
      title: "Wholesale follow-up calls",
      description: "Call 3 warm leads",
      brand_id: BRAND_ID,
      due_date: new Date(Date.now() + 2 * 86400000).toISOString(),
      repeat_frequency: null,
      completed: false,
    },
    {
      id: generateId(),
      title: "Review weekly KPIs",
      description: "Update dashboard numbers",
      brand_id: BRAND_ID,
      due_date: new Date(Date.now() + 5 * 86400000).toISOString(),
      repeat_frequency: "weekly",
      completed: false,
    },
  ];

  return {
    brands: [SEED_BRAND],
    tasks,
    goals,
    ideas,
    kpis,
    reminders,
    playbooks: [] as import("./types").Playbook[],
    weeklyReviews: [] as import("./types").WeeklyReview[],
  };
}
